services:
  web:
    build:
      context: .
      dockerfile: PRO/dockerfile
    container_name: django-web
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped